---

- set_fact:
    custom_boottidal_hs: False

- block:
  - include_role:
      name: "roles/ugens-{{ item }}"
    vars:
      editor: "{{ vscode.editor }}"
    with_items: "{{ sc_ugens }}"

  - set_fact:
      custom_boottidal_hs: True
    when: '"mutable-instruments" in sc_ugens'

  when: sc_ugens is defined

- block:
  - name: install vscode tidalcycles extension
    shell: code --install-extension tidalcycles.vscode-tidalcycles 
    register: vstidin
    changed_when: "not vstidin.stdout is search('All the requested packages are already installed:')"
  
  - name: install vscode haskell syntax extension
    shell: code --install-extension justusadam.language-haskell
    register: vshaskin
    changed_when: "not vshaskin.stdout is search('All the requested packages are already installed:')"
  
  - name: create/replace VSCode ~/.config/Code/User/settings.json (taking a backup)
    template:
      src: templates/settings.json.template
      dest: "/home/{{ansible_env.SUDO_USER}}/.config/Code/User/settings.json"
      mode: 0640
      backup: yes
    tags:
    - config

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'
